AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - nl.cyberworkz.airport::airport-arrival
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AirportArrivalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nl.cyberworkz.airport.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/airport-arrival-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AirportArrivalApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AirportArrivalApi